//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Firmalar
    {
        public short ID { get; set; }
        public string AD { get; set; }
        public string YETKILISTATU { get; set; }
        public string YETKILIADSOYAD { get; set; }
        public string TELEFON1 { get; set; }
        public string TELEFON2 { get; set; }
        public string TELEFON3 { get; set; }
        public string MAIL { get; set; }
        public string FAX { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string ADRES { get; set; }
    }
}
