//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urunler
    {
        public int ID { get; set; }
        public string URUNAD { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public string YIL { get; set; }
        public Nullable<short> ADET { get; set; }
        public Nullable<decimal> ALISFIYAT { get; set; }
        public Nullable<decimal> SATISFIYAT { get; set; }
        public string DETAY { get; set; }
    }
}
